packages:
  - apps/*
  - packages/*
catalogs:
  dev:
    '@types/node': ^25
    '@types/react': ^19
    '@types/react-dom': ^19
    typescript: ^5
  prod:
    '@base-ui/react': ^1.2.0
    '@cdlab996/genid': ^1.2.1
    '@next/third-parties': 16.1.6
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    lucide-react: ^0.575.0
    next: 16.1.6
    next-themes: ^0.4.6
    ogl: ^1.0.11
    radix-ui: ^1.4.3
    react: ^19
    react-dom: ^19
    shadcn: ^3.8.5
    sonner: ^2.0.7
    tailwind-merge: ^3.5.0
    tw-animate-css: ^1.4.0
